# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
# Fabric Properties
# check these on https://modmuss50.me/fabric.html
minecraft_version=26.1

loader_version=0.19.1
# Mod Properties
mod_version=1.3
maven_group=org.simpleautoattack
archives_base_name=SimpleAutoAttack
# Dependencies
# check this on https://modmuss50.me/fabric.html
fabric_version=0.145.1+26.1
# Cloth Config
cloth_config_version=26.1.154
# ModMenu
modmenu_version=18.0.0-alpha.8
